<?php

namespace Database\Seeders;

use App\Models\Event;
use App\Models\User;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::query()->where('email', '=', 'florian.hellmann@student.wb-hochschule.com')->first();
        if ($user) {
            Event::factory()->createMany([
                /*  already added to Informatik seeder
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: BSRAPS',
                    'description' => 'Schriftliche Prüfung Betriebssysteme und Rechnerarchitektur',
                    'location' => 'online',
                    'related_id' => 5,
                    'related_type' => 'BSRAPS',
                    'is_editable' => true,
                    'start' => '2021-10-23 11:00:00',
                    'end' => '2021-10-23 13:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2021-10-23 11:00:00',
                    'updated_at' => '2021-10-23 13:00:00',
                ],
                */
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-INF01XX',
                    'description' => 'B-Prüfung Einführungsprojekt für Informatiker',
                    'location' => 'online',
                    'related_id' => 6,
                    'related_type' => 'B-INF01XX',
                    'is_editable' => true,
                    'start' => '2021-07-20 13:00:00',
                    'end' => '2021-07-20 13:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2021-07-20 13:00:00',
                    'updated_at' => '2021-07-20 13:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: GDIAPS',
                    'description' => 'Schriftliche Prüfung Grundlagen der Informatik',
                    'location' => 'online',
                    'related_id' => 7,
                    'related_type' => 'GDIAPS',
                    'is_editable' => true,
                    'start' => '2021-07-17 09:00:00',
                    'end' => '2021-07-17 11:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2021-07-17 09:00:00',
                    'updated_at' => '2021-07-17 09:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-GOPB01XX',
                    'description' => 'B-Prüfung Grundlagen der objektorientierten Programmierung',
                    'location' => 'online',
                    'related_id' => 8,
                    'related_type' => 'B-GOPB01XX',
                    'is_editable' => true,
                    'start' => '2021-08-20 13:00:00',
                    'end' => '2021-08-20 13:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2021-08-20 13:00:00',
                    'updated_at' => '2021-08-20 13:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: MGIPS',
                    'description' => 'Schriftliche Prüfung Mathematische Grundlagen für Informatiker',
                    'location' => 'online',
                    'related_id' => 9,
                    'related_type' => 'MGIPS',
                    'is_editable' => true,
                    'start' => '2021-07-17 15:00:00',
                    'end' => '2021-07-17 17:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2021-07-17 15:00:00',
                    'updated_at' => '2021-07-17 15:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-EIS01XX ',
                    'description' => 'B-Prüfung Einführung in die IT-Sicherheit',
                    'location' => 'online',
                    'related_id' => 10,
                    'related_type' => 'B-EIS01XX ',
                    'is_editable' => true,
                    'start' => '2021-11-20 13:00:00',
                    'end' => '2021-11-20 13:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2021-11-20 13:00:00',
                    'updated_at' => '2021-11-20 13:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-RBW01XX',
                    'description' => 'B-Prüfung Recht und Betriebswirtschaftslehre',
                    'location' => 'online',
                    'related_id' => 11,
                    'related_type' => 'B-RBW01XX',
                    'is_editable' => true,
                    'start' => '2022-02-19 08:00:00',
                    'end' => '2022-02-19 08:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2022-02-19 08:00:00',
                    'updated_at' => '2022-02-19 08:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: RBWPS',
                    'description' => 'Schriftliche Prüfung Recht und Betriebswirtschaftslehre',
                    'location' => 'online',
                    'related_id' => 12,
                    'related_type' => 'RBWPS',
                    'is_editable' => true,
                    'start' => '2022-02-12 08:00:00',
                    'end' => '2022-02-12 10:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2022-02-12 08:00:00',
                    'updated_at' => '2022-02-12 08:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: SEIBPS',
                    'description' => 'Schriftliche Prüfung Software Engineering',
                    'location' => 'online',
                    'related_id' => 13,
                    'related_type' => 'SEIBPS',
                    'is_editable' => true,
                    'start' => '2022-02-11 14:00:00',
                    'end' => '2022-02-11 16:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2022-02-11 14:00:00',
                    'updated_at' => '2022-02-11 14:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: WMAPS',
                    'description' => 'Schriftliche Prüfung Weiterführende Mathematik',
                    'location' => 'online',
                    'related_id' => 14,
                    'related_type' => 'WMAPS',
                    'is_editable' => true,
                    'start' => '2022-04-09 17:00:00',
                    'end' => '2022-04-09 19:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2022-04-09 17:00:00',
                    'updated_at' => '2022-04-09 17:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: ITICPS',
                    'description' => 'Schriftliche Prüfung Informationstechnologie',
                    'location' => 'online',
                    'related_id' => 15,
                    'related_type' => 'ITICPS',
                    'is_editable' => true,
                    'start' => '2022-10-08 11:00:00',
                    'end' => '2022-10-08 13:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2022-10-08 11:00:00',
                    'updated_at' => '2022-10-08 11:00:00',
                ],[
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-ICM01XX',
                    'description' => 'B-Prüfung Interkulturelle Kompetenz',
                    'location' => 'online',
                    'related_id' => 16,
                    'related_type' => 'B-ICM01XX',
                    'is_editable' => true,
                    'start' => '2023-02-08 11:00:00',
                    'end' => '2023-02-08 11:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2023-02-08 11:00:00',
                    'updated_at' => '2023-02-08 11:00:00',
                ],[
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-PWAA01XX',
                    'description' => 'B-Prüfung Projektmanagement und wissenschaftliches Arbeiten',
                    'location' => 'online',
                    'related_id' => 17,
                    'related_type' => 'B-PWAA01XX',
                    'is_editable' => true,
                    'start' => '2022-12-08 11:00:00',
                    'end' => '2022-12-08 11:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2022-12-08 11:00:00',
                    'updated_at' => '2022-12-08 11:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: SDAPS',
                    'description' => 'Schriftliche Prüfung Sicherheit von Informationen und Anwendungen',
                    'location' => 'Prüfungsstandort Hamburg',
                    'related_id' => 18,
                    'related_type' => 'SDAPS',
                    'is_editable' => true,
                    'start' => '2022-10-08 08:00:00',
                    'end' => '2022-10-08 10:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2022-10-08 08:00:00',
                    'updated_at' => '2022-10-08 08:00:00',
                ],[
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: BPP-Bericht',
                    'description' => 'Bericht Berufspraktische Phase',
                    'location' => 'online',
                    'related_id' => 19,
                    'related_type' => 'BPP',
                    'is_editable' => true,
                    'start' => '2022-10-08 11:00:00',
                    'end' => '2022-10-08 11:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2021-07-01 08:00:00',
                    'updated_at' => '2021-07-01 08:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: DBIAPS',
                    'description' => 'Schriftliche Prüfung Datenbanken',
                    'location' => 'Prüfungsstandort Hamburg',
                    'related_id' => 20,
                    'related_type' => 'DBIAPS',
                    'is_editable' => true,
                    'start' => '2023-02-08 11:00:00',
                    'end' => '2023-02-08 13:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2023-02-08 11:00:00',
                    'updated_at' => '2023-02-08 11:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-MUMA01XX',
                    'description' => 'B-Prüfung Multimediale Anwendungen',
                    'location' => 'online',
                    'related_id' => 21,
                    'related_type' => 'B-MUMA01XX',
                    'is_editable' => true,
                    'start' => '2023-03-10 10:00:00',
                    'end' => '2023-03-10 10:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2023-03-10 10:00:00',
                    'updated_at' => '2023-03-10 10:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: SRN1PS',
                    'description' => 'Schriftliche Prüfung Sicherheit von Systemen',
                    'location' => 'Prüfungsstandort Hamburg',
                    'related_id' => 22,
                    'related_type' => 'SRN1PS',
                    'is_editable' => true,
                    'start' => '2023-04-01 14:00:00',
                    'end' => '2023-04-01 16:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2023-04-01 14:00:00',
                    'updated_at' => '2023-04-01 14:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-AKI01XX',
                    'description' => 'B-Prüfung Anwendung künstlicher Intelligenz',
                    'location' => 'online',
                    'related_id' => 23,
                    'related_type' => 'B-AKI01XX',
                    'is_editable' => true,
                    'start' => '2023-06-08 11:00:00',
                    'end' => '2023-06-08 11:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2023-06-08 11:00:00',
                    'updated_at' => '2023-06-08 11:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: SRN2PS ',
                    'description' => 'Schriftliche Prüfung Sicherheit von Netzwerken',
                    'location' => 'Prüfungsstandort Hamburg',
                    'related_id' => 24,
                    'related_type' => 'SRN2PS ',
                    'is_editable' => true,
                    'start' => '2023-09-16 10:00:00',
                    'end' => '2023-09-16 12:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2023-09-16 10:00:00',
                    'updated_at' => '2023-09-16 10:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: VIIDPS',
                    'description' => 'Schriftliche Prüfung Verteilte Informationsverarbeitung',
                    'location' => 'Prüfungsstandort Hamburg',
                    'related_id' => 25,
                    'related_type' => 'VIIDPS',
                    'is_editable' => true,
                    'start' => '2023-12-09 12:30:00',
                    'end' => '2023-12-09 14:30:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2023-12-09 12:30:00',
                    'updated_at' => '2023-12-09 12:30:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: WFP1PS',
                    'description' => 'Schriftliche Prüfung Weiterführende Programmierung in C und C++',
                    'location' => 'Prüfungsstandort Hamburg',
                    'related_id' => 26,
                    'related_type' => 'WFP1PS',
                    'is_editable' => true,
                    'start' => '2023-09-16 12:30:00',
                    'end' => '2023-09-16 14:30:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2023-09-16 12:30:00',
                    'updated_at' => '2023-09-16 12:30:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-CSI01XX',
                    'description' => 'B-Prüfung/ Laboreingangsprüfung Modul Labor Cybersicherheit',
                    'location' => 'online',
                    'related_id' => 27,
                    'related_type' => 'B-CSI01XX',
                    'is_editable' => true,
                    'start' => '2023-11-16 12:00:00',
                    'end' => '2023-11-16 12:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2023-11-16 12:00:00',
                    'updated_at' => '2023-11-16 12:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: KFIAPM',
                    'description' => 'Mündliche Prüfung Kommunikation und Führung',
                    'location' => 'online',
                    'related_id' => null,
                    'related_type' => null,
                    'is_editable' => true,
                    'start' => '2024-01-25 18:00:00',
                    'end' => '2024-01-25 21:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2024-01-25 18:00:00',
                    'updated_at' => '2024-01-25 18:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Abgabetermin: B-ISM01XX',
                    'description' => 'B-Prüfung IT-Sicherheit-Management',
                    'location' => 'online',
                    'related_id' => null,
                    'related_type' => null,
                    'is_editable' => true,
                    'start' => '2024-02-19 14:00:00',
                    'end' => '2024-02-19 14:00:00',
                    'is_full_day' => true,
                    'external_id' => null,
                    'created_at' => '2024-02-19 14:00:00',
                    'updated_at' => '2024-02-19 14:00:00',
                ],
                [
                    'user_id' => $user->id,
                    'key' => 'exam',
                    'title' => 'Prüfungstermin: Projektpräsentation',
                    'description' => 'Projektpräsentation Matjesbrötchen',
                    'location' => 'online',
                    'related_id' => null,
                    'related_type' => null,
                    'is_editable' => true,
                    'start' => '2024-02-03 14:00:00',
                    'end' => '2024-02-03 16:00:00',
                    'is_full_day' => false,
                    'external_id' => null,
                    'created_at' => '2024-02-03 14:00:00',
                    'updated_at' => '2024-02-03 14:00:00',
                ],
            ]);
        } else {
            // Falls der Benutzer nicht gefunden wurde, gibt eine Meldung aus
            echo "Benutzer nicht gefunden. Bitte überprüfen Sie die Benutzer-ID im Seeder.\n";
        }
    }
}
