<?php

namespace Database\Seeders;

use App\Models\Task;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::query()->find(2);
        if ($user) {
            Task::factory()->createMany([
                [
                    'title' => 'Einf - Einführungsveranstaltung',
                    'user_id' => $user->id,
                    'description' => 'Anmelden zur Veranstaltung,
                    Veranstaltung durchführen',
                    'status' => 'done',
                    'module_id' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BSI01a - UNIX Eine Einführung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BSI02a - Nutzung des Betriebssystems UNIX',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BSI03 - Rechnerarchitekturen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BSI04 - Betriebssysteme',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BSI05 - Betriebssysteme II',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BSI06 - Rechnerarchitektur II',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BSRAPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'INF-L - Einführungsprojekt für Informatiker',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'INFPL - Einführungsprojekt für Informatiker',
                    'user_id' => $user->id,
                    'description' => 'An Veranstaltung teilnehmen',
                    'status' => 'done',
                    'module_id' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-INF01XX - Einführungsprojekt für Informatiker',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten,',
                    'status' => 'done',
                    'module_id' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'GDI01 - Einführung in die Informatik',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'TGI01 - Datenstrukturen und Algorithmen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'TGI02 - Algorithmen und Komplexität',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'GDIAPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'PYTHBU - Theis: Einstieg in Python',
                    'user_id' => $user->id,
                    'description' => 'Buch durcharbeiten bzw. teilweise durcharbeiten',
                    'status' => 'done',
                    'module_id' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'PYTH00 - Begleitheft zu PYTHBU',
                    'user_id' => $user->id,
                    'description' => 'A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'JAPR01 - Programmieren mit Java I',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'JAPR02 - Programmieren mit Java II',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-GOPB01XX - Grundlagen der objektorientierten Programmierung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI01A - Grundlagen der Mathematik Teil 1a: Mengen, Zahlenmengen, Vollständige Induktion',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI01C - Grundlagen der Mathematik Teil 1C: Komplexe Zahlen, Relationen, Finanzmathematik.',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI17 - Lineare Algebra: Lineare Gleichungssysteme und Matrizen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI03 - Grundlagen der Logik',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI24 - Funktionenlehre',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI10 - Stochastik I',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MGIPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'EIS01 - Grundlagen der Informations- und IT-Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'EIS02 - Angriffe und Bedrohungen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'EIS03 - Malware',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'EIS04 - Der Faktor Mensch in der Informationssicherheit',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-EIS01XX - Einführung in die IT-Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'RLB01 - Grundlagen des Zivilrechts',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],[
                    'title' => 'BWI01 - Betriebswirtschaftliche Grundlagen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'RLB02 - Grundlagen des Arbeitsrechts',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BWI02 - Organisatorische Strukturen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MMG03B - Recht in der Medienwirtschaft',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BWI03 - Unternehmensführung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BWI04 - Material- und Produktionswirtschaft',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BWI05 - Absatz und Marketing',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-RBW01XX - Recht',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'RBWPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SEI11 - Phasenmodelle und Planung von Softwareprojekten',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SEI12 - Unified Modeling Language',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SEI13 - Entwurfsmuster',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SEI04 - Objektorientierte Systementwicklung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SEI14 - Grundlagen der Softwarearchitektur',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SEIBPS - Software Engineering',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 21,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI06 - Vektoralgebra und Analytische Geometrie',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI09 - Reihen und Integraltransformationen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI13 - Gewöhnliche Differenzialgleichungen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI14c - Numerische Methoden',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MAI11 - Stochastik II',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'WMAPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 22,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ITI21 - Grundlagen moderner Computernetze',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ITI22 - Informationstheoretische und physikalisch-technische Grundlagen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ITI23 - Bitübertragung und Netzzugang',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ITI24 - TCP/IP-Protokollfamilie',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ITI25 - Internetworking und Netzdesign',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ITI26 - Anwendungsdienste und Netzmanagement',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ITICPS - Informationstechnologie',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 23,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'INMT01 - Intercultural Communication',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 24,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'INMT02 - Global Strategies, Regional Implementation',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 24,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-ICM01XX - Interkulturelle Kompetenz',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 24,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'IMI03 - Projektmanagement',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 25,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM08Z - Führungsaspekte des Projektmanagements',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 25,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'WAM02 - Wissenschaftliches Arbeiten Teil 1 – Einführung und Grundlagen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 25,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'WAM03 - Wissenschaftliches Arbeiten Teil 2 – Forschungsmethoden und methodisch gestütztes Vorgehen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 25,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'WAM04 - Wissenschaftliches Arbeiten Teil 3 – Systematische Literaturauswertung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 25,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-PWAA01XX - Projektmanagement und wissenschaftliches Arbeiten',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 25,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SDA01 - Kryptografie',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 26,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SDA02 - Sichere Entwicklung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 26,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SDA03 - Identity Management',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 26,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SDA04 - Sichere Datenspeicherung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen,
                    Studienheft nacharbeiten (markieren, zusammenfassen, etc.),
                    A-Aufgaben bearbeiten,
                    B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 26,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SDAPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 26,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Berufspraktische Phase',
                    'user_id' => $user->id,
                    'description' => 'Arbeit suchen,
                    Arbeiten,
                    Arbeit Dokumentieren,
                    Berichtsinhalt mit Chef klären',
                    'status' => 'done',
                    'module_id' => 27,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'BPP - Bericht',
                    'user_id' => $user->id,
                    'description' => 'Dokumentationen durchgehen,
                    Bericht schreiben,
                    Chef prüfen lassen',
                    'status' => 'done',
                    'module_id' => 27,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'DBI11 - Theoretische Grundlagen von DB-Systemen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'DBI12 - Technische Grundlagen von DB-Systemen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'DBI13 - Datenbanksprachen am Beispiel SQL',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'DBI14 - Datenbankanwendungen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'DBI15 - Datenbanken in Webanwendungen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'DBI05 - Verteilte Datenbanken',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-DBI02XX - Datenbanken',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'DBIAPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 28,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MMI12 - Kommunikation im Web und clientseitige Websprachen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 29,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MMI11 - Multimedia-Grundlagen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 29,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MMI13 - Serverseitige Websprachen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 29,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'MMI14 - Web-Anwendungen: Applikationen und Frameworks',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 29,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-MUMA01XX - Multimediale Anwendungen',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 29,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN01 - Physische Sicherheit und Hochverfügbarkeit',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 30,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN02 - Grundlagen eines sicheren IT-Betriebs',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 30,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN06 - Mobile Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 30,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN1PS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 30,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'VII11 - Grundlagen verteilter Informationssysteme',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 31,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'VII12 - Grundlagen von Computernetzwerken',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 31,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'VII13 - Interprozess-Kommunikation',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 31,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'VII14 - Programmierung für verteilte Systeme',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 31,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'VII15 - Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 31,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'VIIDPS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 31,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'KII01a - Grundlagen der Künstlichen Intelligenz',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 32,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'KII02 - Logische Programmierung mit Prolog',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 32,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'KII03a - Expertensysteme und Genetische Algorithmen',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 32,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'KII04a - Künstliche Neuronale Netze',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 32,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-AKI01XX - Anwendung künstlicher Intelligenz',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 32,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM01Z - Mitarbeiter führen und motivieren',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM02Z - Grundlagen der Führung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM09Z - Führung und Konfliktlösung',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM05Z - Führungstechniken und Führungsinstrumente',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM03Z - Führung und Kommunikation',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM-O10Z - WBT Moderation',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'FUM10aZ - Führung und Moderation',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'KFIAPM - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Moderation üben',
                    'status' => 'open',
                    'module_id' => 33,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'PRJR - Projektstart',
                    'user_id' => $user->id,
                    'description' => 'Team suchen,
                    Thema besprechen,
                    Veranstaltung besuchen',
                    'status' => 'done',
                    'module_id' => 34,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ProPräsentation - Projektpräsentation',
                    'user_id' => $user->id,
                    'description' => 'Matjesbrötchen auf Silbertablett präsentieren',
                    'status' => 'open',
                    'module_id' => 34,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Projekt ausarbeiten',
                    'user_id' => $user->id,
                    'description' => 'Matjesbrötchen belegen',
                    'status' => 'in_progress',
                    'module_id' => 34,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Projektarbeit - Projektarbeit',
                    'user_id' => $user->id,
                    'description' => 'Das Belegen ausführlich beschreiben und alle Dokumentierten Schritte zusammenfassen',
                    'status' => 'open',
                    'module_id' => 34,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN03 - Firewall-Systeme',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 35,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN04 - Intrusion Detection und Intrusion Prevention',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 35,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN05 - Sichere Netzwerkkommunikation',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 35,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'SRN2PS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     Übungsklausuren durcharbeiten',
                    'status' => 'done',
                    'module_id' => 35,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'GPI21 - Programmieren in C - Teil 1',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 37,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'GPI22 - Programmieren in C - Teil 2',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 37,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'GPI15 - Programmieren in C++ Teil 1',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 37,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'GPI16 - Programmieren in C++ Teil 2',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 37,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'WFP1PS - Vorbereitung',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte überfliegen,
                     Zusammenfassungen durcharbeiten,
                     Lernzettel/ Karteikarten schreiben,
                     programmieren,
                     programmieren und mehr programmieren',
                    'status' => 'done',
                    'module_id' => 37,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ISM01 - IT-Sicherheitsmanagement I',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 38,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ISM02 - IT-Sicherheitsmanagement II',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'open',
                    'module_id' => 38,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'ISM04 - IT-Forensik – Grundlagen, Standards, Rechtliche Aspekte, Werkzeuge',
                    'user_id' => $user->id,
                    'description' => 'Studienheft durchlesen, Studienheft nacharbeiten (markieren, zusammenfassen, etc.), A-Aufgaben bearbeiten, B-Aufgaben bearbeiten',
                    'status' => 'done',
                    'module_id' => 38,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-ISM01XX - IT-Sicherheit-Management',
                    'user_id' => $user->id,
                    'description' => 'Studienhefte durchgehen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 38,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'CSI-L - Laborbeschreibung Cyber-Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Laborvorbereitung, lesen und verstehen, Vorlage für B-CSI01',
                    'status' => 'done',
                    'module_id' => 39,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-CSI01XX - Laboreingangsprüfung Cyber-Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Linux vertiefen,
                    B-Prüfung bearbeiten',
                    'status' => 'done',
                    'module_id' => 39,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'CSISem - Auftaktveranstaltung Cyber-Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'An Veranstalltung teilnehmen,
                    Linux vertiefen',
                    'status' => 'in_progress',
                    'module_id' => 39,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'CSILab - Labor Cyber-Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Aufgaben aus Seminar bearbeiten',
                    'status' => 'open',
                    'module_id' => 39,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'B-CSI02XX - Laborabschlussprüfung Cyber-Sicherheit',
                    'user_id' => $user->id,
                    'description' => 'Gelerntes aus Seminar anwenden,
                    B-Prüfung bearbeiten',
                    'status' => 'open',
                    'module_id' => 39,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Exposé ',
                    'user_id' => $user->id,
                    'description' => 'Thesis-Thema suchen, Professor finden, einarbeiten ins Thema, Exposé schreiben',
                    'status' => 'done',
                    'module_id' => 40,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Thesis',
                    'user_id' => $user->id,
                    'description' => 'Viel Arbeit',
                    'status' => 'open',
                    'module_id' => 40,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'title' => 'Kolloquium',
                    'user_id' => $user->id,
                    'description' => 'Getane Arbeit verteidigen',
                    'status' => 'done',
                    'module_id' => 40,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }
        else {
            // Falls der Benutzer nicht gefunden wurde, gibt eine Meldung aus
            echo "Benutzer nicht gefunden. Bitte überprüfen Sie die Benutzer-ID im Seeder.\n";
        }

    }
}
